### ISSUE TITLE
How to provide and consume service that extends http

### ISSUE THREAD

**Issue by danwulff** [filipesilva/angular-quickstart-lib#11]
I was looking to create a custom "auth" service that would apply some custom headers when http calls are made. I've done this before within an angular-cli project, but haven't had much success trying to implement within the quickstart-lib, likely due to myself not fully understanding how compilation works for libraries.

I've created a fork of this quickstart-lib here: https://github.com/danwulff/angular-quickstart-lib

Issue:
`ERROR Error: No provider for XHRBackend!` is seen when trying to consume the service.

Reproduce:
`git clone https://github.com/danwulff/angular-quickstart-lib`
`cd angular-quickstart-lib`
`npm install`
`npm run start`

Notice the console errors.

Note: I was able to consume the LibService just fine after importing HttpModule into the Demo app.module: https://github.com/danwulff/angular-quickstart-lib/commit/eb8b0dd152e95d5483eb54d29e0394497d118252

But is there a way to have the library provide the XHRBackend dependency properly to not require the user to import HttpModule alongside a service?

**Comment by ValeryVS** [comment]
I think, you need, at least, provide XHRBackend and RequestOptions as providers.

**Comment by filipesilva** [comment]
@ValeryVS's comment sounds about right. You need to provide those two since you have them as dependencies in `deps: [XHRBackend, RequestOptions]`. You can do it in your `src/lib/src/module.ts`.

**Comment by danwulff** [comment]
Thanks @ValeryVS however, when I add `XHRBackend` and `RequestOptions` to providers I get this ```Error: (SystemJS) Can't resolve all parameters for RequestOptions: (?).```

https://github.com/danwulff/angular-quickstart-lib has been updated with providers listed.

**Comment by ValeryVS** [comment]
@danwulff Read the "Appendix: Dependency Management" in the 
https://github.com/filipesilva/angular-quickstart-lib/blob/master/README.md
it is not as strait forward as `@angular/cli`. With this kit you can control build process, but you must do a few more steps for it.
You need to include `@angular/http` in SystemJS configs in demo app and integration app for testing (actually, it is already here) and in the `build.js` (there is only `@angular/core`).
