### ISSUE TITLE
Support for demo app templateUrl

### ISSUE THREAD

**Issue by anjmao** [filipesilva/angular-quickstart-lib#12]
Hi, thanks for great quickstart :)

I missed ability to load demo app component html from templateUrl. Maybe you can add system-angular-loader.js to system.js meta section or I can create PR, because I already have this setup and it works fine.

**Comment by filipesilva** [comment]
I meant to add that but then forgot actually. Would you like to create a PR for it? I'd ask it to be as similar to the https://github.com/angular/quickstart/ setup for `system-angular-loader.js` please.

**Comment by anjmao** [comment]
Yes, I will do it soon.

**Comment by anjmao** [comment]
@filipesilva I created [PR](https://github.com/filipesilva/angular-quickstart-lib/pull/15)

**Comment by filipesilva** [comment]
Closed via https://github.com/filipesilva/angular-quickstart-lib/pull/15
