### ISSUE TITLE
Support git publishing via new prepare script

### ISSUE THREAD

**Issue by intellix** [filipesilva/angular-quickstart-lib#13]
So it seems that since npm 5 you can now install dependencies via Github and it'll install devDependencies and run a `prepare` script.

This would mean we don't need to publish packages via `npm` and it makes it easier to fork and install from forks etc.

So then you can do:
```
npm i https://github.com/filipesilva/angular-quickstart-lib
```

And it'll work out of the box without a publish

**Comment by filipesilva** [comment]
The path changes in `package.json` are problematic, since the published directory structure needs to be as is at the moment per the packaging spec.

Plus I don't think npm5 should be a hard requirement. For those two reasons, I'm not sure we should make these changes.

**Comment by intellix** [comment]
alright sounds cool to me. Will use the change and enforce the team to use NPM 5 >:) 
One thing I saw though is that the umd had the wrong path

**Comment by filipesilva** [comment]
Oh that's a mistake, thanks for letting me know!
