### ISSUE TITLE
angular-cli reads es2015 format

### ISSUE THREAD

**Issue by sebelga** [filipesilva/angular-quickstart-lib#18]
I am facing an issue and can't seem to see where it comes from.
When I import the package created with the build script from angular-quickstart-lib inside my angular-cli project, I get an error when building the app in production mode (with uglifyj.js)

Uglify js complains about an "Unexpected token operator «=», expected punc «,»" which comes from the es2015 js file and is an es2015 feature.

My package has all the "main", "es2015" and "module" pointing to the good corresponding file, but for some reason the angular cli build keeps on loading my es2015 version (and thus breaks the uglify.js that expect an es5 apparently).

I would appreciate some help on how to target the good ES version for angular-cli. cheers!

[Edit] I do have my tsconfig.json with "target": "es5"

**Comment by filipesilva** [comment]
That's odd, Angular CLI targets the `module` entry and so should be using `libname.es5.js`. Do you have your library somewhere I can look at?

**Comment by loixlab** [comment]
Sorry it's a private package so I can't show it. Maybe it's worth mentioning that I made a scoped package and this is the final folder structure (removing src folders):

```
package.json
LICENCE
README
/dist
    index.d.ts
    ux-core.d.ts
    ux-core.es5.js
    ux-core.js
    ux-core.metadata.json
    /bundles
        ux-core.umd.js
        ux-core.umd.min.js
```

----
And here is my package.json

```json
{
  "_args": [
    [
      {
        "raw": "@eui/ux-core@0.0.2-11",
        "scope": "@eui",
        "escapedName": "@eui%2fux-core",
        "name": "@eui/ux-core",
        "rawSpec": "0.0.2-11",
        "spec": "0.0.2-11",
        "type": "version"
      },
      "c:\\opsys\\opsys-ui\\src\\main\\angular"
    ]
  ],
  "_from": "@eui/ux-core@0.0.2-11",
  "_id": "@eui/ux-core@0.0.2-11",
  "_inCache": true,
  "_location": "/@eui/ux-core",
  "_nodeVersion": "7.10.0",
  "_npmUser": {},
  "_npmVersion": "4.2.0",
  "_phantomChildren": {},
  "_requested": {
    "raw": "@eui/ux-core@0.0.2-11",
    "scope": "@eui",
    "escapedName": "@eui%2fux-core",
    "name": "@eui/ux-core",
    "rawSpec": "0.0.2-11",
    "spec": "0.0.2-11",
    "type": "version"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "author": "",
  "dependencies": {},
  "description": "",
  "engines": {
    "node": ">= 6.9.0",
    "npm": ">= 3.0.0"
  },
  "es2015": "dist/ux-core.js",
  "files": [
    "dist",
    "LICENSE"
  ],
  "license": "MIT",
  "main": "dist/bundles/ux-core.umd.js",
  "module": "dist/ux-core.es5.js",
  "name": "@eui/ux-core",
  "optionalDependencies": {},
  "peerDependencies": {
    "@angular/core": ">=4.0.0 <5.0.0 || >=4.0.0-beta <5.0.0",
    "@angular/http": ">=4.0.0 <5.0.0 || >=4.0.0-beta <5.0.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.2",
    "@ngrx/store": "^2.2.1",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "reselect": "^2.5.4",
    "rxjs": "^5.0.1"
  },
  "readme": "# Warning\r\n\r\nThis quickstart is under active development and hasn't yet reached its final form.\r\n\r\nIt may not be fully compatible with current versions of Angular.\r\n\r\n# Angular QuickStart Lib\r\n[![Build Status][travis-badge]][travis-badge-url]\r\n\r\nThis is a simple library quickstart for Angular libraries, implementing the\r\n[Angular Package Format v4.0](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#heading=h.k0mh3o8u5hx).\r\n\r\nCurrently only unscoped, primary entry-point libraries are supported.\r\n\r\nFeatures:\r\n- a simple example library\r\n- unit tests for the library\r\n- a demo application that consumes the library in JIT mode and runs in watch mode\r\n- an integration app that consumes the library in JIT and AOT mode and runs e2e tests\r\n\r\nCommon tasks are present as npm scripts:\r\n\r\n- `npm start` to run a live-reload server with the demo app\r\n- `npm run test` to test in watch mode, or `npm run test:once` to only run once\r\n- `npm run build` to build the library\r\n- `npm run lint` to lint \r\n- `npm run clean` to clean\r\n- `npm run integration` to run the integration e2e tests\r\n- `npm install ./relative/path/to/lib` after `npm run build` to test locally in another app\r\n\r\nIf you need to debug the integration app, please check `./integration/README.md`.\r\n\r\n[travis-badge]: https://travis-ci.org/filipesilva/angular-quickstart-lib.svg?branch=master\r\n[travis-badge-url]: https://travis-ci.org/filipesilva/angular-quickstart-lib\r\n",
  "readmeFilename": "README.md",
  "repository": {},
  "typings": "dist/ux-core.d.ts",
  "version": "0.0.2-11"
}

```

thanks!

**Comment by filipesilva** [comment]
I tried using the default lib in a Angular CLI project and didn't run into the error you mentioned. Stuff seemed to just work with and without `--prod`. I'm unsure what's happening in your case...

**Comment by loixlab** [comment]
The error that I receive when running `ng build --prod -sm` is

```
ERROR in vendor.d5cf0021c9b80f17f746.bundle.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./~/@eui/ux-core/dist/ux-core.js:28,0][vendor.d5cf0021c9b80f17f746.bundle.js:36790,42]
```

Which leads me to think that it is reading from "ux-core.js" instead of "ux-core.es5.js"

Thanks for any help

**Comment by filipesilva** [comment]
Well, we can test that easily. How about you go into `node_modules` and delete the es2015 file manually?

**Comment by loixlab** [comment]
I receive a not found error

```
Module not found: Error: Can't resolve '@eui/ux-core/dist/ux-core'
```

It's extremely strange as my folder structure + the package.json is the same as the packages from @angular...  It might be my machine or npm or ...

**Comment by loixlab** [comment]
I added my package in a fresh angular-cli project and it does build perfectly. :+1:  
Definitely something in the other project dependencies or something.
Thanks for looking into it and for this great starter lib.

**Comment by filipesilva** [comment]
Glad you got it sorted!

**Comment by loixlab** [comment]
I have managed to nail exactly what was the problem in case other might do something similar.
I was exporting in my index.ts an "alias" to another module export. Exactly:

```js
export { Store } from '@ngrx/store';
```

So I could do something like this in my Components

```
import { Store, entitiesState } from '@eui/ux-core'
```

It did work in the past with another build I had with rollup, and probably another tsconfig or something. But now it does not anymore.
