### ISSUE TITLE
Hide generated files in lib/src folder

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [filipesilva/angular-quickstart-lib#23]
Coming from an angular CLI background, I'm used to only see the development files during development. I've started trying to build a lib with this project (thanks for the work!) and the generated .js and .map files show up among others. I assume that when I start using sass that the generated css files show up as well. This makes development more complicated, ideally I'd only see the development files during development. Is this feasible? 

(btw I know I can hide file/folder patterns in my IDE)

Thanks!

**Comment by loixlab** [comment]
In Visual Studio Code it very easy. You can add this to the "files.exclude" setting

```
"**/*.js": {"when": "$(basename).ts"},
"**/*.map": {"when": "$(basename)"}
```

And also the .css if you need to.

[EDIT] ups! sorry I just read your last line. Ok you knew about it... leaving this for others :)

**Comment by danwulff** [comment]
@sebelga yup, just have to place that in a files.exclude parameter ala (vscode):
```
"files.exclude": {
    "**/*.css": { "when": "$(basename).scss" },
    "**/*.js": { "when": "$(basename).ts" },
    "**/*.map": { "when": "$(basename).map" }
},
```

And then @tobi-or-not-tobi just add the .css, .js and .map to your .gitignore ¯\\_(ツ)_/¯
```
src/**/*.js
src/**/*.css
*.js.map
*.css.map
e2e/**/*.js
e2e/**/*.js.map
```

**Comment by tobi-or-not-tobi** [comment]
@sebelga @danwulff thanks for the response. This works, I guess I was just hoping for a solution that would store the generated files in memory or somewhere else. I was not aware of the $(basename) feature, which is great (my assumption was that I wouldn't see any .js or .css files anymore in the IDE without writing explicit file paths).

**Comment by filipesilva** [comment]
I do what @sebelga and @danwulff suggest myself. This starter doesn't really do things in memory like the CLI does, so that's the only way.
