### ISSUE TITLE
404: /base/src/demo/systemjs-angular-loader.js

### ISSUE THREAD

**Issue by Crazyht** [filipesilva/angular-quickstart-lib#27]
Hi, 

I have use your repo as base for my ngx-tree-select package, on my local environment all run correctly, but on travis I take : 

`
> karma start karma.conf.js --single-run
25 06 2017 20:25:33.336:WARN [watcher]: Pattern "/home/travis/build/Crazyht/ngx-tree-select/src/demo/systemjs-angular-loader.js" does not match any file.
25 06 2017 20:25:33.706:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
25 06 2017 20:25:33.708:INFO [launcher]: Launching browser Chrome with unlimited concurrency
25 06 2017 20:25:33.714:INFO [launcher]: Starting browser Chrome
25 06 2017 20:25:35.004:INFO [Chrome 59.0.3071 (Linux 0.0.0)]: Connected on socket pk0b_Q8V37KLLylpAAAA with id 95296274
25 06 2017 20:25:35.765:WARN [web-server]: 404: /base/src/demo/systemjs-angular-loader.js
Chrome 59.0.3071 (Linux 0.0.0) ERROR
`

You can see full travis result : [here](https://travis-ci.org/Crazyht/ngx-tree-select/builds/246872740)
Problem is on [https://github.com/Crazyht/ngx-tree-select](https://github.com/Crazyht/ngx-tree-select) [dev branch].

Where I m wrong or miss something ? 

Thanks,
Crazyht

**Comment by Crazyht** [comment]
I have found, git don't commit src/demo/systemjs-angular-loader.js on my repo :(

**Comment by filipesilva** [comment]
Heya, you probably need to add this line to your git ignore so the file isn't ignored: https://github.com/filipesilva/angular-quickstart-lib/blob/master/.gitignore#L9

**Comment by Crazyht** [comment]
Yeah strange vscode can stash file but first commit with GitKraken ignore same :)
