### ISSUE TITLE
Suggestion: Lightweight gh-pages

### ISSUE THREAD

**Issue by Crazyht** [filipesilva/angular-quickstart-lib#28]
Deploy SystemJS to gh-pages in state is little heavy (copy node_modules), but normally all node packages can be accessed by https://unpkg.com/... so may be best way is to create script which copy /src/demo in temp folder replace path for 'npm' from 'node_modules/' to 'https://unpkg.com/' and deploy temp folder as gh-pages. 

What do you think about this ? I'm wrong ?
(and optionally this script can be integrate to travis process for success build)

**Comment by filipesilva** [comment]
No, you're not wrong, that's a good approach. It's just that this repro tries to follow the quickstart format, and make the least possible changes. While doing that has it's benefits, it's one more thing to explain for a particular scenario.

**Comment by filipesilva** [comment]
Also, overall it would be much better to bundle the app using Angular CLI, or rollup+aot.
