### ISSUE TITLE
Sass compilation

### ISSUE THREAD

**Issue by kondi0** [filipesilva/angular-quickstart-lib#34]
Hi,

I am trying to build a library wit a component that contains .scss file. 

It seems that sass files doesn't compile. 

How could I compile .scss?

Thanks!

**Comment by e-cloud** [comment]
checkout https://github.com/e-cloud/ngx-tree, see if it helps

**Comment by Bengreen** [comment]
i had same issue and took the updated inline_resources.js file form ngx-tree and used it inside this repo and it worked nicely.

**Comment by filipesilva** [comment]
Have a look at https://github.com/filipesilva/angular-quickstart-lib/issues/6, a couple of options are discussed there.
