### ISSUE TITLE
Multiple libs

### ISSUE THREAD

**Issue by jogelin** [filipesilva/angular-quickstart-lib#4]
Hello,

This repo is very interesting, thx ! 

As many people, I would like to setup a repo (monorepo) with shared libraries:
- Angular 2 modules/components/services
- Simple Typescript libs
- Configurations/tools
- ...

What do you think of having more than one lib in your repo ? And a build script for building these librairies with cross-dependencies, shared configuration, etc.. Also usable on a CI environment.

For the moment I am mixing a lot of JS/shell scripts, dependencies, etc... to achieve this goal...:(

**Comment by filipesilva** [comment]
Hi there,

Having multiple libraries in a single repo is a very common usecase, but out of scope for this repo. I'm only focusing on single library for now.
