### ISSUE TITLE
Discussion: There is no need of demo application in library seed

### ISSUE THREAD

**Issue by kmolerov** [filipesilva/angular-quickstart-lib#45]
I think that having demo application inside seed project, only creates confusion. Seed should be bare-bone library. 
It is trivial to create demo app manually with angular-cli and add the library with npm link. 
My preference is to always have minimalistyc approach when I have to try new things. 
My proposal: delete "demo" folder and merge "src/lib"->"lib".

**Comment by EliCDavis** [comment]
I'll weigh in with my hobbyist level opinion.

I don't think that having a demo causes any confusion. Most libraries I see have a demo folder and it only seems appropriate. Also having that demo folder might make a user of this seed to be more inclined to actually build one, thus providing more documentation of the library they develop (people get a demonstration plus they can also always look at the demo's source).

I will however say, the [library I developed](https://github.com/EliCDavis/ng-conditionally-validate) does not follow the src/lib folder structure, but has a src and demo folders at the root of my repository. But I have seen other libraries do the same thing this starter seed is.

**Comment by ghost** [comment]
I don't believe it create confusion at all. I use it as a 'kitchen-sink' that gets built and deployed to a gh-pages repo in our internal github. That allows other devs to check out the functionality of the components they're importing and also acts as an inventory of what we have in the library.

I also use it to make sure the library is working the way I want while I'm developing it.

I would not want to see it changed.

**Comment by ttma1046** [comment]
The demo folder here is not only for demo also for quickly testing the components in the library visually. If like what you said，create another demo application via angular-cli and npm link means I need to npm run build my library with a lot of imagination and confidence instead of testing ，even take a look at my components in my library，then npm publish，npm install and ng serve the demo app？？
