### ISSUE TITLE
Thought/Guidance for Encapsulating and Exposing Components in NgModules

### ISSUE THREAD

**Issue by chrisalexander55** [filipesilva/angular-quickstart-lib#5]
First of all thank you for exposing this repo for vetting Angular-based library projects. Based on this configuration, I have been able to successfully author, test and publish a few assets for use within my organization. Although you state in the README that this is for simple libraries, what is the evolving thought/guidance for encapsulating and exposing various component types in NgModules, i.e. ChartsModule, MultiMediaModule, etc. Thanks!

**Comment by filipesilva** [comment]
Heya, I have to mention that that this quickstart isn't finalized yet. It may not be fully compatible with Angular.

You should be able to export whatever you want though, it's not limited in that sense. Encapsulating and exposing components in NgModules follows the same logic as it would inside your application.

https://angular.io/docs/ts/latest/guide/ngmodule.html would be the current available guidance. Do you feel like it should be expanded with library specific information? Off the top of my head I don't see any specific caveat.

**Comment by chrisalexander55** [comment]
I think adding a few exposed ngModule types could be of benefit: 

1. Service module as Provider and when/when not to use "forRoot()" vs "forChild()" in root application vs. lazy-loading config, respectively
2. UI module that demos wrapping a few pure components with entryComponents list config

As you know, there are Pipes, Directives, Validators, Animations, etc. that could also be NgModule encapsulated examples but these 2 types examples cover what, IMHO, must library developers seek to get started with.

This is a work-in-progress for me also and I hope to shift my organizations front-end developers to pivot into library contributors rather than non-resuable, one-shot component authors. I'll be more than happy to contribute over the next weeks.

**Comment by chrisalexander55** [comment]
I have a use case where modularizing at multiple levels is throwing the following exception:

`> tsc -p src/demo/

src/demo/app/app.component.ts(2,10): error TS2305: Module '"/Users/x201413/Projects/pru-lib-ng3/src/lib/index"' has no exported member 'TestComponent'.
src/demo/app/app.component.ts(3,10): error TS2305: Module '"/Users/x201413/Projects/pru-lib-ng3/src/lib/index"' has no exported member 'ComponentsModule'.`

Here is my TestComponent.ts

`import { Component } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'test-component',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.css']
})
export class TestComponent {
  name = 'Angular Library';
}`

The test.component.html

`<h2>Hello {{name}}</h2>`

A components.module.ts

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { TestComponent } from './test/test.component';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [
    TestComponent
  ],
  entryComponents: [
    TestComponent
  ]
})
export class ComponentsModule { }`

The lib.module.ts

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ComponentsModule } from './components/components.module';

@NgModule({
  imports: [
    CommonModule,
    AnimationsModule,
    AttributesModule,
    ComponentsModule,
    PipesModule,
    ServicesModule,
    ValidatorsModule
  ],
  exports: [
    AnimationsModule,
    AttributesModule,
    ComponentsModule,
    PipesModule,
    ServicesModule,
    ValidatorsModule
  ],
  declarations: []
})
export class LibModule {}`

And finally, index.ts

`export { LibModule } from './src/lib.module';`

Did I miss something?

**Comment by tomwayson** [comment]
@filipesilva 

>  I have to mention that that this quickstart isn't finalized yet. It may not be fully compatible with Angular.

Since the status of [this document](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#) says "last update: 2017-04-07, status: implemented" can we assume that the format itself is finalized, but just that this quickstart may not fully implement the final format yet?
