### ISSUE TITLE
Unexpected value 'LibModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by mina-skunk** [filipesilva/angular-quickstart-lib#54]
`npm run build`
`cd .\dist`
`npm link`

From @angular/cli@1.3.2 project add:
src/tsconfig.app.json
```
  "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
```
src/app/app.module.ts
```
import { LibModule } from 'quickstart-lib';
...
  imports: [
    BrowserModule,
    LibModule
  ],
...
```

`npm link quickstart-lib`
`npm start` or `ng serve --preserve-symlinks`

> Unexpected value 'LibModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by baruchvlz** [comment]
You can see [here](https://github.com/filipesilva/angular-quickstart-lib/blob/master/package.json#L2) that the name of the package is `quickstart-lib` and not `lib`. (unless you changed it).

Try doing `import { LibModule } from 'quickstart-lib'`

**Comment by mina-skunk** [comment]
@baruchvlz That was a typo sorry, if so the error would be:

> Cannot find module 'lib'.

It is just working now though so closing.
