### ISSUE TITLE
Cannot run integration

### ISSUE THREAD

**Issue by lazarljubenovic** [filipesilva/angular-quickstart-lib#58]
#### Repro steps

1. Clone the repo
2. Run `npm i && npm run integration`

#### Result

Chrome opens, and I see the "connected to BS" badge, but it just says "Loading...". Console logs that it `Could not find Angular on page http://localhost:8080/ : retries looking for angular exceeded` twice, and then fails both tests.

Also check out [the complete output](https://pastebin.com/uwwaZRkM) I get. 

I'm on `node v7.6.0` and `npm 5.4.1` on Ubuntu. Will get my hands on a Mac in ~12 hours and will post the results from there as well.

**Comment by mmmichl** [comment]
This is probably a duplicate, see #41

**Comment by lazarljubenovic** [comment]
You're right, thanks. Closing this then as a duplicate of https://github.com/filipesilva/angular-quickstart-lib/issues/41.
